server:
  port: 2222
spring:
  dataSource:
    dynamic:
      primary: xingluo_xingshi
      datasource:
        xingluo_xingshi:
          url: jdbc:mysql://localhost:3306/xingluo_xingshi?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&useSSL=false&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: wsw2852006
# logging
logging:
  level:
    root: info
    org.example.mapper: debug

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:/mapper/*/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    # 关闭MP3.0自带的banner
    banner: true
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      # 默认数据库表下划线命名
      table-underline: true